add apollo using apollo guide
calebmer/exponent-docs pull request #1
Opened 2017-01-03 23:50 UTC by calebmer

2017-01-03 23:57 UTC, stubailo requested changes
Looks great, just a few changes, in particular the code sample uses HTML.

2017-01-03 23:57 UTC, stubailo commented on versions/unversioned/guides/using-apollo.rst
> +The `Apollo <http://www.apollodata.com/>`_ client makes it much easier for you
I don't think we have to emphasize "much easier" since this is the only section of the docs that talks about GraphQL at all AFAIK.

2017-01-03 23:57 UTC, stubailo commented on versions/unversioned/guides/using-apollo.rst
> +Combined with a static type system, GraphQL provides both a powerful user
Word "experience" is used twice.

2017-01-03 23:57 UTC, stubailo commented on versions/unversioned/guides/using-apollo.rst
> +      networkInterface: createNetworkInterface({ uri: 'http://my-api.graphql.com' }),
Maybe throw a `/graphql` on the end of the URL for good measure.

2017-01-03 23:57 UTC, stubailo commented on versions/unversioned/guides/using-apollo.rst
> +`react-apollo <https://www.npmjs.com/package/react-apollo>`_ package.
Might be worth mentioning that this is similar to Redux? IDK

2017-01-03 23:57 UTC, stubailo commented on versions/unversioned/guides/using-apollo.rst
> +          <ul>
This isn't React native code AFAIK. might be easy to steal from Learn Apollo React Native example

2017-01-03 23:57 UTC, stubailo commented on versions/unversioned/guides/using-apollo.rst
> +2. A `GitHub API Example <https://github.com/apollostack/GitHub-GraphQL-API-Example>`_ built to work with GitHub’s new GraphQL API.
Let's add a link to the Learn Apollo Exponent tutorial at the bottom?

2017-01-04 00:03 UTC, calebmer commented on versions/unversioned/guides/using-apollo.rst
> +`react-apollo <https://www.npmjs.com/package/react-apollo>`_ package.
I thought so initially too, so I’ll add it. I didn’t want to do that unless Redux had been mentioned somewhere else in the docs.

2017-01-04 00:04 UTC, stubailo commented on versions/unversioned/guides/using-apollo.rst
> +`react-apollo <https://www.npmjs.com/package/react-apollo>`_ package.
I think in today's world it's pretty safe to assume everyone using React is familiar with Redux, and the Exponent starter app has it AFAIK

2017-01-04 00:06 UTC, calebmer commented on versions/unversioned/guides/using-apollo.rst
> +          <ul>
Whoops, good catch.

2017-01-04 01:06 UTC, stubailo commented
Looks great! Let's send the PR!

2017-01-04 02:09 UTC, stubailo commented on versions/unversioned/guides/using-apollo.rst
> +1. Incrementally adoptable.
These are a bit vague - I think we should make them more detailed or change them to something Exponent users would care more about.

2017-01-04 21:44 UTC, closed without merging